version: '3.3'

volumes:
  static_value:
  media_value:


services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:      
      - ./.env

  backend:
    image: chp13/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media/

    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: chp13/foodgram_front:latest
    volumes:
      - ../frontend/:/app/result_build/
      - static_value:/var/html/static/

    depends_on:
      - backend


  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/


    depends_on:
      - frontend
