version: '3.8'
services:

  db:
    image: dagistanik:13.0-alpine
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: "foodgram:dev"
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
        - django-static:/code/static
        - django-media:/code/media
  
  frontend:
    image: dagistanik/foodgram_front:latest

  
  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./logs/:/var/log/nginx/
      - django-static:/var/html/static_backend/
      - django-media:/var/html/media/

volumes:
  pg_data:
  django-static:
  django-media:

